### ISSUE TITLE
Looks like some accordion advice is in tabs section

### ISSUE THREAD

**Issue by anevins12** [katekalcevich/Test-ARIA#3]
In the README the following section is in the Tabs advice:
> What I've done instead for keybard interaction is:
> you can tab through all accordions and see which accordion has the focus (Focus outlines are provided for buttons by browsers, as long as you haven't removed them using CSS. If you removed the outline, put it back.)
you can open a tab using the the enter key or spacebar

Is that intentional?

**Comment by katekalcevich** [comment]
Great catch - no, not intentional. I did a lot of copy/paste and missed that one. I've fixed it.
