### ISSUE TITLE
aria-landmark-roles.html: Search role & div support

### ISSUE THREAD

**Issue by anevins12** [katekalcevich/Test-ARIA#4]
File: /aria-landmark-roles.html

Would there be wider support using `role="search"` on the `<form>` element instead of `<div>`? 

Current code:
```
<div role="search">
        <form>Search goes here</form>
</div>
```

That's part of Mozilla's prefered method (under best practices): https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role

**Comment by katekalcevich** [comment]
Indeed you are correct. I had referenced Adrian's article about where to put the search role https://adrianroselli.com/2015/08/where-to-put-your-search-role.html but failed to read his update at the bottom of the article! I'll fix this now, but add the caveat that validators may throw a warning.

**Comment by scottaohara** [comment]
Worth noting that if a validator throws a warning for this, that's a bug with the validator.

**Comment by katekalcevich** [comment]
Actually, on further reading, I think it's not even relevant to include that note. The W3C validators are updated and validating correctly, so I'll take it out entirely and update the reference links.
