### ISSUE TITLE
aria-landmark-roles.html: Should roles be doubled with HTML?

### ISSUE THREAD

**Issue by anevins12** [katekalcevich/Test-ARIA#5]
File: /aria-landmark-roles.html

Should ARIA roles be used here when HTML5 elements are used?

```
<header role="banner">
    ...
</header>

<footer role="contentinfo">
     ...
</footer>
```

In regards to the README advice:
> No need to double up HTML and ARIA (for example, <main role="main"> unless you are supporting a specific browser and screen reader combination that doesn't support the landmarks you are using

**Comment by katekalcevich** [comment]
Thanks for catching that. I've updated the readme to reflect why I have that demo page:

When I tested with VoiceOver, the combo HTML and ARIA landmarks file is the only one that announced all the landmarks.
