### ISSUE TITLE
landmarks

### ISSUE THREAD

**Issue by scottaohara** [katekalcevich/Test-ARIA#6]
A few things about the landmarks content:

- role=application is not a landmark.
- "don't nest" is unclear in your rules, especially when also indicating only one can be used per page.  So what are you saying don't nest within?
- typically there should be only a single banner/contentinfo on a page, but there may be multiple header/footer elements.  The rules do not distinguish between these allowances.  It would be helpful to note that using multiple header/footer elements _can_ result in bugs were multiple banner/contentinfo landmarks are exposed incorrectly.  
- rule for role=search reads oddly "Don't use on a element - put it on a parent div"  is it missing a word?  Per #4, it could well (and should) be used on a `<form>`.
- role=region/section rule should state "requires a label to be exposed as a landmark"  However, use of generic region landmarks should be cautioned against unless absolutely necessary.
- rule for `role=form` is unnecessary.

**Comment by katekalcevich** [comment]
Thanks Scott. I really appreciate your expertise here and I've updated the content based on your feedback.
